"""Timestamp policy (plan §16).

All timestamps are UTC. Ownership-critical timestamps are generated by SQLite
using a single subsecond expression so that the lease lifecycle, heartbeats,
adoption and cancellation requests all share one clock. Python-generated
timestamps are never mixed into ownership-critical paths.
"""

from __future__ import annotations

from sqlalchemy import func, literal

# Single canonical format used everywhere ownership-critical (plan §16).
TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%fZ"

# Central timestamp SQL expression for all persisted M1 timestamps (plan §6).
# Used as a server_default/DEFAULT and in explicit UPDATEs; never mix in Python
# wall-clock time for persisted domain timestamps.
DB_NOW_SQL = f"strftime('{TIMESTAMP_FORMAT}','now')"


# --- Column-expression forms (for use in ORM/Core queries) -----------------


def db_now():
    """SQLite-authoritative current UTC timestamp as a column expression.

    Renders:  strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    """
    return func.strftime(TIMESTAMP_FORMAT, literal("now"))


def db_now_minus(seconds: int):
    """SQLite-authoritative UTC timestamp `seconds` in the past (column expr).

    Renders:  strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-N seconds')
    """
    return func.strftime(TIMESTAMP_FORMAT, literal("now"), f"-{int(seconds)} seconds")


# --- Raw-SQL string forms (for use inside text() statements in ownership.py) -
# These share one source of truth for the format and remain DB-authoritative.


def db_now_sql() -> str:
    """SQL fragment: strftime('%Y-%m-%dT%H:%M:%fZ', 'now')."""
    return f"strftime('{TIMESTAMP_FORMAT}','now')"


def db_now_minus_sql(seconds: int) -> str:
    """SQL fragment: strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-N seconds')."""
    return f"strftime('{TIMESTAMP_FORMAT}','now','-{int(seconds)} seconds')"
