"""Ownership module (plan §49–§60).

All lease/ownership fencing lives here. Critical ownership operations own their
own transactions and execute atomically on a single checked-out SQLite
connection under ``BEGIN IMMEDIATE``. They do NOT accept an externally managed
``AsyncSession`` for the critical transaction, and higher layers never manually
compose a lease SELECT + a separate Generation UPDATE.

The proven low-level pattern (see scripts/probe_begin_immediate.py and
tests/test_ownership_transaction.py) is:

    async with engine.connect() as conn:
        await conn.exec_driver_sql("BEGIN IMMEDIATE")
        try:
            ...authority check + protected mutation on `conn`...
            await conn.exec_driver_sql("COMMIT")
        except Exception:
            await conn.exec_driver_sql("ROLLBACK")
            raise

M0 scope: the *lease* functions are fully implemented. The *Generation*
ownership helpers from plan §49 are declared as part of the module's documented
API but raise ``NotImplementedError`` — they are implemented in M3B once the
``generations`` table exists (M1).

Worker identity (plan §8): ``worker_id`` is generated by the *caller*
(``soloring.worker.runtime``) as ``str(uuid.uuid4())`` at process startup and
passed in here. This module never generates, loads, or persists worker IDs.
"""

from __future__ import annotations

import contextlib
from contextlib import asynccontextmanager
from dataclasses import dataclass
from enum import Enum

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from soloring.db.timeutil import db_now_minus_sql, db_now_sql

# Stable singleton lease role (plan §30). The worker_id is ephemeral; this name
# is the durable authority identity.
LEASE_NAME = "generation-worker"


# --- Result taxonomies (plan §53, §59) --------------------------------------


class LeaseAcquisitionResult(str, Enum):
    """Why a lease-authority cycle ended the way it did (plan §53)."""

    ACQUIRED_NEW = "acquired_new"
    REFRESHED_SELF = "refreshed_self"
    TAKEN_OVER = "taken_over"
    HELD_BY_OTHER = "held_by_other"


class LeaseRetentionResult(str, Enum):
    """Outcome of a heartbeat refresh (plan §56)."""

    RETAINED = "retained"
    LOST = "lost"


class OwnershipMutationResult(str, Enum):
    """Outcome of an ownership-fenced Generation mutation (plan §59)."""

    OK = "ok"
    LEASE_LOST = "lease_lost"
    GENERATION_OWNERSHIP_LOST = "generation_ownership_lost"
    GENERATION_NOT_ACTIVE = "generation_not_active"
    NOT_FOUND = "not_found"
    # The Generation is active and owned, but not in the state this mutation
    # requires (e.g. one-way submission-state ordering violation).
    GENERATION_STATE_CONFLICT = "generation_state_conflict"


class SubmissionPermission(str, Enum):
    """One-shot submission authority decision (M5 plan §8, as amended).

    Only the stack frame whose fenced transition not_started →
    submission_possible committed receives MAY_POST. Every later path —
    crash recovery, adoption, requeue, a second call — receives
    REDISCOVER_ONLY and is forbidden from invoking the remote submission.
    """

    MAY_POST = "may_post"
    REDISCOVER_ONLY = "rediscover_only"
    LEASE_LOST = "lease_lost"
    GENERATION_OWNERSHIP_LOST = "generation_ownership_lost"
    GENERATION_NOT_ACTIVE = "generation_not_active"
    # Caller ordering bug (e.g. marking possible before persisting the
    # submission artifact, or a mismatched attempt id). Never grants POST.
    SUBMISSION_STATE_CONFLICT = "submission_state_conflict"


@dataclass(frozen=True)
class LeaseSnapshot:
    """Read-only view of the singleton lease for diagnostics/standby."""

    name: str
    worker_id: str
    acquired_at: str
    heartbeat_at: str


# --- The proven BEGIN IMMEDIATE transaction primitive -----------------------


@asynccontextmanager
async def _immediate_transaction(engine: AsyncEngine):
    """One checked-out connection, one BEGIN IMMEDIATE, COMMIT/ROLLBACK (§50).

    The authority check and the protected mutation performed inside this block
    share a single connection and a single SQLite transaction, so no other
    writer can interleave between them (verified by tests, including the
    negative split-connection test in test_ownership_transaction.py).
    """
    conn = await engine.connect()
    committed = False
    try:
        await conn.exec_driver_sql("BEGIN IMMEDIATE")
        try:
            yield conn
            await conn.exec_driver_sql("COMMIT")
            committed = True
        except Exception:
            if not committed:
                with contextlib.suppress(Exception):
                    await conn.exec_driver_sql("ROLLBACK")
            raise
    finally:
        await conn.close()


# --- Lease functions (M0) ---------------------------------------------------


async def acquire_worker_lease(
    engine: AsyncEngine,
    worker_id: str,
    ttl_seconds: int,
) -> LeaseAcquisitionResult:
    """Acquire or confirm the singleton generation-worker lease (plan §52).

    Inside one ``BEGIN IMMEDIATE``:

      * lease missing                         -> insert            -> ACQUIRED_NEW
      * same worker_id already owns           -> refresh heartbeat -> REFRESHED_SELF
      * another worker owns + heartbeat stale -> replace owner     -> TAKEN_OVER
      * another worker owns + fresh           -> deny              -> HELD_BY_OTHER

    All staleness is computed in database time (plan §16, §52).
    """
    async with _immediate_transaction(engine) as conn:
        row = (
            await conn.execute(
                text(
                    "SELECT worker_id, heartbeat_at FROM worker_leases "
                    "WHERE name = :name"
                ),
                {"name": LEASE_NAME},
            )
        ).one_or_none()

        if row is None:
            await conn.execute(
                text(
                    "INSERT INTO worker_leases "
                    "(name, worker_id, acquired_at, heartbeat_at) "
                    f"VALUES (:name, :wid, {db_now_sql()}, {db_now_sql()})"
                ),
                {"name": LEASE_NAME, "wid": worker_id},
            )
            return LeaseAcquisitionResult.ACQUIRED_NEW

        if row.worker_id == worker_id:
            await conn.execute(
                text(
                    f"UPDATE worker_leases SET heartbeat_at = {db_now_sql()} "
                    "WHERE name = :name AND worker_id = :wid"
                ),
                {"name": LEASE_NAME, "wid": worker_id},
            )
            return LeaseAcquisitionResult.REFRESHED_SELF

        # Another worker owns the lease. Take over only if its heartbeat is stale.
        takeover = await conn.execute(
            text(
                "UPDATE worker_leases "
                "SET worker_id = :wid, "
                f"    acquired_at = {db_now_sql()}, heartbeat_at = {db_now_sql()} "
                "WHERE name = :name AND heartbeat_at < " + db_now_minus_sql(ttl_seconds)
            ),
            {"name": LEASE_NAME, "wid": worker_id},
        )
        if takeover.rowcount == 1:
            return LeaseAcquisitionResult.TAKEN_OVER
        return LeaseAcquisitionResult.HELD_BY_OTHER


async def refresh_worker_lease(
    engine: AsyncEngine,
    worker_id: str,
) -> LeaseRetentionResult:
    """Conditional lease heartbeat refresh (plan §56).

    The WHERE clause fences the write: only the current owner can keep the lease
    fresh. A worker that has lost the lease (or never held it) gets LOST.
    """
    async with _immediate_transaction(engine) as conn:
        result = await conn.execute(
            text(
                f"UPDATE worker_leases SET heartbeat_at = {db_now_sql()} "
                "WHERE name = :name AND worker_id = :wid"
            ),
            {"name": LEASE_NAME, "wid": worker_id},
        )
        return (
            LeaseRetentionResult.RETAINED
            if result.rowcount == 1
            else LeaseRetentionResult.LOST
        )


async def verify_execution_authority(
    engine: AsyncEngine, worker_id: str, generation_id: str
) -> OwnershipMutationResult:
    """Proof of CURRENT authority, immediately before an EXTERNAL side
    effect (re-audit R2).

    RETAINING semantics (third re-gate): inside ONE ``BEGIN IMMEDIATE``,
    the singleton-lease heartbeat is refreshed CONDITIONALLY (owner must
    still be `worker_id`) and the Generation's owner/status verified. A
    caller that passes therefore holds a FRESH lease interval — an expired
    lease cannot be stolen out from under the external effect between this
    check and the call. This is the single central primitive for that
    gate; call sites must not improvise scattered worker_id reads.

    Returns OK, LEASE_LOST, GENERATION_OWNERSHIP_LOST, NOT_FOUND, or
    GENERATION_NOT_ACTIVE (terminal row).
    """
    async with _immediate_transaction(engine) as conn:
        refreshed = await conn.execute(
            text(
                f"UPDATE worker_leases SET heartbeat_at = {db_now_sql()} "
                "WHERE name = :name AND worker_id = :wid"
            ),
            {"name": LEASE_NAME, "wid": worker_id},
        )
        if refreshed.rowcount != 1:
            return OwnershipMutationResult.LEASE_LOST
        row = (
            await conn.execute(
                text(
                    "SELECT worker_id, status FROM generations WHERE id = :gid"
                ),
                {"gid": generation_id},
            )
        ).one_or_none()
        if row is None:
            return OwnershipMutationResult.NOT_FOUND
        if row.worker_id != worker_id:
            return OwnershipMutationResult.GENERATION_OWNERSHIP_LOST
        if row.status in TERMINAL_STATUSES:
            return OwnershipMutationResult.GENERATION_NOT_ACTIVE
        return OwnershipMutationResult.OK


async def read_lease(engine: AsyncEngine) -> LeaseSnapshot | None:
    """Read the singleton lease without taking a write lock (diagnostics)."""
    async with engine.connect() as conn:
        row = (
            await conn.execute(
                text(
                    "SELECT name, worker_id, acquired_at, heartbeat_at "
                    "FROM worker_leases WHERE name = :name"
                ),
                {"name": LEASE_NAME},
            )
        ).one_or_none()
    if row is None:
        return None
    return LeaseSnapshot(
        name=row.name,
        worker_id=row.worker_id,
        acquired_at=row.acquired_at,
        heartbeat_at=row.heartbeat_at,
    )


async def is_lease_authority(
    engine: AsyncEngine,
    worker_id: str,
) -> bool:
    """Cheap read-only check: does `worker_id` currently hold the lease?"""
    snap = await read_lease(engine)
    return snap is not None and snap.worker_id == worker_id


# --- Generation ownership helpers (M3A happy path; M3B adds recovery) -------
# All fenced exactly like the lease functions: one connection, one BEGIN
# IMMEDIATE, lease-authority check AND generation-ownership check inside the
# same transaction (v0.1 §58-§60, F16-F20).

TERMINAL_STATUSES = ("succeeded", "failed", "interrupted", "cancelled")


async def _fenced_generation_mutation(
    engine: AsyncEngine,
    worker_id: str,
    generation_id: str,
    require_active: bool,
    statements: list[tuple[str, dict]],
) -> OwnershipMutationResult:
    """Run lease+ownership-verified statements atomically (plan §58).

    Each entry in `statements` is (SQL, params). Returns OK on commit,
    GENERATION_NOT_ACTIVE when the generation is terminal, NOT_FOUND when
    missing, or the ownership-loss codes.
    """
    from sqlalchemy import text

    async with _immediate_transaction(engine) as conn:
        lease = (
            await conn.execute(
                text(
                    "SELECT worker_id FROM worker_leases WHERE name = :name"
                ),
                {"name": LEASE_NAME},
            )
        ).one_or_none()
        if lease is None or lease.worker_id != worker_id:
            return OwnershipMutationResult.LEASE_LOST

        row = (
            await conn.execute(
                text(
                    "SELECT worker_id, status FROM generations WHERE id = :gid"
                ),
                {"gid": generation_id},
            )
        ).one_or_none()
        if row is None:
            return OwnershipMutationResult.NOT_FOUND
        if row.worker_id != worker_id:
            return OwnershipMutationResult.GENERATION_OWNERSHIP_LOST
        if require_active and row.status in TERMINAL_STATUSES:
            return OwnershipMutationResult.GENERATION_NOT_ACTIVE

        for sql, params in statements:
            await conn.execute(text(sql), params)
        return OwnershipMutationResult.OK


async def claim_next_generation(
    engine: AsyncEngine, worker_id: str
) -> tuple[str, str] | None:
    """Claim the oldest queued Generation (plan §60).

    BEGIN IMMEDIATE → verify singleton lease → select oldest queued →
    conditional preparing/worker_id/claimed_at/heartbeat_at update. Two
    workers can never claim the same Generation: the write lock is held for
    the whole read-decide-write sequence.

    Returns (generation_id, attempt_id). The attempt_id is minted inside the
    claim transaction and scopes all staging for THIS execution attempt
    (M3A review: data/staging/<generation-id>/<attempt-id>/), so a stale
    worker from a previous attempt can never collide with, overwrite, or
    contaminate the current attempt's staging namespace.
    """
    from sqlalchemy import text
    from uuid import uuid4

    async with _immediate_transaction(engine) as conn:
        lease = (
            await conn.execute(
                text("SELECT worker_id FROM worker_leases WHERE name = :name"),
                {"name": LEASE_NAME},
            )
        ).one_or_none()
        if lease is None or lease.worker_id != worker_id:
            return None

        # All queued candidates in order (audit F15): a single corrupt row
        # (illegal modern submission state on a queued generation) is logged
        # loudly and SKIPPED — it must not permanently starve every valid
        # job behind it. The corrupt row itself is an operator-visible
        # invariant failure, never silently reset.
        rows = (
            await conn.execute(
                text(
                    "SELECT id, executor_submission_state FROM generations "
                    "WHERE status = 'queued' ORDER BY queued_at"
                )
            )
        ).all()
        row = next((r for r in rows
                    if r.executor_submission_state == "not_started"), None)
        skipped = sum(
            1 for r in rows if r.executor_submission_state != "not_started"
        )
        if skipped:
            import logging

            logging.getLogger("soloring.worker.ownership").error(
                "INVARIANT: %d queued generation(s) carry illegal "
                "submission state; refusing to claim them (skipped, not "
                "reset) — operator attention required",
                skipped,
            )
        if row is None:
            return None

        attempt_id = str(uuid4())
        claimed = await conn.execute(
            text(
                "UPDATE generations SET status = 'preparing', worker_id = :wid, "
                "attempt_id = :attempt, "
                "executor_submission_state = 'not_started', "
                "submission_possible_at = NULL, "
                f"claimed_at = {db_now_sql()}, heartbeat_at = {db_now_sql()} "
                "WHERE id = :gid AND status = 'queued'"
            ),
            {"wid": worker_id, "gid": row.id, "attempt": attempt_id},
        )
        if claimed.rowcount != 1:  # unreachable under IMMEDIATE; defensive
            return None
        return row.id, attempt_id


async def heartbeat_owned_generation(
    engine: AsyncEngine, worker_id: str, generation_id: str
) -> OwnershipMutationResult:
    sql = (
        f"UPDATE generations SET heartbeat_at = {db_now_sql()} "
        "WHERE id = :gid AND worker_id = :wid AND status NOT IN "
        "('succeeded','failed','interrupted','cancelled')"
    )
    result = await _fenced_generation_mutation(
        engine, worker_id, generation_id, require_active=True,
        statements=[(sql, {"gid": generation_id, "wid": worker_id})],
    )
    return result


async def update_owned_generation_progress(
    engine: AsyncEngine,
    worker_id: str,
    generation_id: str,
    current: int,
    total: int,
    node: str | None,
) -> OwnershipMutationResult:
    sql = (
        f"UPDATE generations SET progress_current = :cur, progress_total = :tot, "
        f"current_node = :node, heartbeat_at = {db_now_sql()}, "
        f"updated_at = {db_now_sql()} "
        "WHERE id = :gid AND worker_id = :wid"
    )
    return await _fenced_generation_mutation(
        engine, worker_id, generation_id, require_active=True,
        statements=[(sql, {"cur": current, "tot": total, "node": node,
                           "gid": generation_id, "wid": worker_id})],
    )


async def transition_owned_generation(
    engine: AsyncEngine,
    worker_id: str,
    generation_id: str,
    to_status: str,
    *,
    error_code: str | None = None,
    error_message: str | None = None,
    started: bool = False,
) -> OwnershipMutationResult:
    """Fenced lifecycle transition (plan §58, §68).

    Terminal transitions stamp completed_at; `started` also stamps
    started_at (preparing→submitted begins lifecycle timing).
    """
    sets = ["status = :status", f"updated_at = {db_now_sql()}"]
    params: dict = {"status": to_status, "gid": generation_id, "wid": worker_id}
    if to_status in TERMINAL_STATUSES:
        sets.append(f"completed_at = {db_now_sql()}")
    if error_code is not None:
        sets.append("error_code = :ecode")
        params["ecode"] = error_code
    if error_message is not None:
        sets.append("error_message = :emsg")
        params["emsg"] = error_message
    if started:
        sets.append(f"started_at = {db_now_sql()}")
    sql = f"UPDATE generations SET {', '.join(sets)} WHERE id = :gid AND worker_id = :wid"
    return await _fenced_generation_mutation(
        engine, worker_id, generation_id, require_active=True,
        statements=[(sql, params)],
    )


async def persist_owned_executor_handle(
    engine: AsyncEngine,
    worker_id: str,
    generation_id: str,
    executor_job_id: str,
    handle_json: str,
) -> OwnershipMutationResult:
    sql = (
        "UPDATE generations SET executor_job_id = :job, executor_handle_json = :hj, "
        f"heartbeat_at = {db_now_sql()} WHERE id = :gid AND worker_id = :wid"
    )
    return await _fenced_generation_mutation(
        engine, worker_id, generation_id, require_active=True,
        statements=[(sql, {"job": executor_job_id, "hj": handle_json,
                           "gid": generation_id, "wid": worker_id})],
    )


# --- Recovery (plan §54, §62-§67) — M3B --------------------------------------


def _stale_cutoff_sql(stale_seconds: int) -> str:
    return db_now_minus_sql(stale_seconds)


async def find_stale_active_generations(
    engine: AsyncEngine, stale_seconds: int
) -> list[dict]:
    """Recovery candidates (plan §62): active, heartbeat stale. Read-only
    scan; the caller (current authority) filters its own worker_id at
    adoption/decision time."""
    from sqlalchemy import text

    cutoff = _stale_cutoff_sql(stale_seconds)
    async with engine.connect() as conn:
        rows = (
            await conn.execute(
                text(
                    "SELECT id, status, worker_id, executor, executor_job_id, "
                    "attempt_id, executor_handle_json, cancel_requested_at "
                    "FROM generations "
                    "WHERE status IN ('preparing','submitted','running','importing') "
                    f"AND heartbeat_at < {cutoff}"
                )
            )
        ).mappings().all()
    return [dict(r) for r in rows]


async def requeue_stale_preparing_generation(
    engine: AsyncEngine, worker_id: str, generation_id: str
) -> OwnershipMutationResult:
    """Requeue a stale preparing Generation (plan §64).

    ONLY safe when no durable executor submission exists — the handle columns
    must be NULL, verified inside the same fenced transaction. queued_at is
    preserved so the request keeps its original queue position; worker
    ownership fields are cleared for the next claim.
    """
    from sqlalchemy import text

    async with _immediate_transaction(engine) as conn:
        lease = (
            await conn.execute(
                text("SELECT worker_id FROM worker_leases WHERE name = :name"),
                {"name": LEASE_NAME},
            )
        ).one_or_none()
        if lease is None or lease.worker_id != worker_id:
            return OwnershipMutationResult.LEASE_LOST

        row = (
            await conn.execute(
                text(
                    "SELECT status, worker_id, attempt_id, executor_job_id, "
                    "executor_handle_json, executor_submission_state "
                    "FROM generations WHERE id = :gid"
                ),
                {"gid": generation_id},
            )
        ).one_or_none()
        if row is None:
            return OwnershipMutationResult.NOT_FOUND
        if row.status != "preparing":
            return OwnershipMutationResult.GENERATION_NOT_ACTIVE
        # M5 amendment §2: requeue is restricted to work with NO modern
        # durable attempt. A non-null attempt_id is never destroyed merely to
        # regain submission permission — such rows are adoption cases.
        if row.attempt_id is not None:
            return OwnershipMutationResult.GENERATION_STATE_CONFLICT
        if row.executor_job_id is not None or row.executor_handle_json is not None:
            # Submission MAY have happened (plan §65 ambiguity): never blindly
            # requeue work that might be running externally.
            return OwnershipMutationResult.GENERATION_NOT_ACTIVE

        await conn.execute(
            text(
                "UPDATE generations SET status = 'queued', worker_id = NULL, "
                "claimed_at = NULL, heartbeat_at = NULL, "
                "executor_submission_state = 'not_started', "
                "submission_possible_at = NULL, "
                f"updated_at = {db_now_sql()} "
                "WHERE id = :gid"
            ),
            {"gid": generation_id},
        )
        return OwnershipMutationResult.OK


async def adopt_stale_generation(
    engine: AsyncEngine, worker_id: str, generation_id: str
) -> OwnershipMutationResult:
    """Adopt a stale active Generation (plan §66): atomic ownership transfer
    to the current authority while verifying the singleton lease."""
    from sqlalchemy import text

    async with _immediate_transaction(engine) as conn:
        lease = (
            await conn.execute(
                text("SELECT worker_id FROM worker_leases WHERE name = :name"),
                {"name": LEASE_NAME},
            )
        ).one_or_none()
        if lease is None or lease.worker_id != worker_id:
            return OwnershipMutationResult.LEASE_LOST

        row = (
            await conn.execute(
                text("SELECT status, worker_id FROM generations WHERE id = :gid"),
                {"gid": generation_id},
            )
        ).one_or_none()
        if row is None:
            return OwnershipMutationResult.NOT_FOUND
        if row.status in TERMINAL_STATUSES:
            return OwnershipMutationResult.GENERATION_NOT_ACTIVE
        if row.worker_id == worker_id:
            return OwnershipMutationResult.OK  # already ours (idempotent)

        await conn.execute(
            text(
                "UPDATE generations SET worker_id = :wid, "
                f"heartbeat_at = {db_now_sql()}, updated_at = {db_now_sql()} "
                "WHERE id = :gid"
            ),
            {"wid": worker_id, "gid": generation_id},
        )
        return OwnershipMutationResult.OK


async def read_cancellation_intent(engine: AsyncEngine, generation_id: str) -> bool:
    """Whether a persisted cancellation request is outstanding (plan §69)."""
    from sqlalchemy import text

    async with engine.connect() as conn:
        val = (
            await conn.execute(
                text(
                    "SELECT cancel_requested_at FROM generations WHERE id = :gid"
                ),
                {"gid": generation_id},
            )
        ).scalar_one_or_none()
    return val is not None


# One-shot submission authority primitives live in their own module but are
# re-exported here so callers have one ownership import surface (M5A-1).
from soloring.worker.submission_state import (  # noqa: E402,F401
    confirm_owned_submission,
    mark_submission_possible,
    mark_submission_uncertain,
    persist_owned_executor_submission,
)

from soloring.worker.submission_state import select_owned_soft_cancel  # noqa: E402,F401
